apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: datacenter
spec:
  selector:
    app: apache-app
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008


apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: datacenter
  labels:
    app: apache-app
spec:
  selector:
    matchLabels:
      app: apache-app
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
      - name: apache
        image: httpd:2.4.28
        ports:
        - containerPort: 8080
          name: httpd 