apiVersion: v1
kind: Service
metadata:
  name: centos-service
  namespace: default
spec:
  selector:
    app: centos-ssh
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: centos-ssh
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30012


apiVersion: apps/v1
kind: Deployment
metadata:
  name:  centos-deployment
  namespace: default
  labels:
    app:  centos-ssh
spec:
  selector:
    matchLabels:
      app: centos-ssh
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: centos-ssh
    spec:
      containers:
      - name:  centos-container
        image:  gcr.io/kodekloud/centos-ssh-enabled:node
        ports:
        - containerPort:  8080
          name:  centos-ssh

