apiVersion: batch/v1beta1 
kind: CronJob
metadata:
  name: datacenter
  namespace: default
spec:
  schedule: "*/6 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-datacenter
            image: httpd:latest
            args: [echo Welcome to Xfusioncorp!]
          restartPolicy: OnFailure