apiVersion: batch/v1 
kind: Job
metadata:
  name: countdown-datacenter
  namespace: default
  labels:
    app: MYAPP
spec:
  template:
    metadata:
      name: countdown-datacenter
      labels:
        app: MYAPP
    spec:
      containers:
      - name: container-countdown-datacenter
        image: debian:latest
        command: ["/bin/sh", "-c"]
        args: ["for i in 10 9 8 7 6 5 4 3 2 1 ; do echo $i; done"]
      restartPolicy: Never