apiVersion: v1 
kind: Secret
metadata:
  name: mysql-root-pass
  namespace: default
type: Opaque
data:
  password: WVVJaWRoYjY2Nwo=
---
apiVersion: v1 
kind: Secret
metadata:
  name: mysql-user-pass
  namespace: default
type: Opaque
data:
  username: a29kZWtsb3VkX2dlbQo=
  password: WWNoWkhSY0xrTAo=
  
---
apiVersion: v1 
kind: Secret
metadata:
  name: mysql-db-url
  namespace: default
type: Opaque
data:
  database: a29kZWtsb3VkX2RiNAo=

---
apiVersion: v1 
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 250Mi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mysql 
  hostPath:
    path: "/var/lib/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: default
  labels:
    app: MYAPP
spec:
  storageClassName: mysql 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi

---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    app: MYAPP
  type: NodePort 
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: myapp
    protocol: TCP
    port: 3306
    targetPort: 3306 
    nodePort: 30007
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
  labels:
    app:  MYAPP
spec:
  selector:
    matchLabels:
      app: MYAPP
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  MYAPP
    spec:
      containers:
      - name: mysql-deployment
        image: mysql:latest
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url 
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pv 
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pv-claim
