apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: default
  labels:
    app: redis-slave
spec:
  selector:
    matchLabels:
      app: redis-slave
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: slave-redis-nautilus
        image: gcr.io/google_samples/gb-redisslave:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: GET_HOSTS_FROM
            value: "dns"
        ports:
        - containerPort: 6379
---
apiVersion: v1 
kind: Service
metadata:
  name: redis-slave
  namespace: default
spec:
  selector:
    app: redis-slave
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379