apiVersion: v1 
kind: Service
metadata:
  name: nagios-service
  namespace: default
spec:
  selector:
    app: MYAPP
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008