apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios-deployment
  namespace: default
  labels:
    app:  MYAPP
spec:
  selector:
    matchLabels:
      app: MYAPP
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  MYAPP
    spec:
      containers:
      - name: nagios-container
        image: jasonrivers/nagios
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80




#creates a password for a new user 
 #htpasswd -c /opt/nagios/etc/htpasswd.users xFusionCorp   