version: '3'
services: 
  db:
    container_name: mysql-db
    ports:
      - "3306:3306"
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - SHOW=true
    volumes:
      - "mysql-volume:/var/lib/mysql"
volumes:
  mysql-volume: