apiVersion: v1 
kind: PersistentVolume
metadata:
  name: pv-devops
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath: 
    path: /mnt/dba

---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: pvc-devops
  namespace: default
  labels:
    app: MYAPP
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1 
kind: Pod
metadata:
  name: pod-devops
  namespace: default
  labels:
    app: MYAPP
spec:
  containers:
  - name: container-devops
    image: nginx:latest
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort: 80
    volumeMounts:
    - name: storage-devops
      mountPath: /usr/share/nginx/html
  volumes:
    - name: storage-devops
      persistentVolumeClaim: 
        claimName: pvc-devops
  restartPolicy: Always 
---
apiVersion: v1 
kind: Service
metadata:
  name: web-devops
  namespace: default
spec:
  selector:
    app: MYAPP
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 30008

