apiVersion: v1
kind: Secret
metadata:
  name: media
  namespace: default
type: Opaque
data:
    license-number: dGltLW1haW5naQ==

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-datacenter
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
  - name: secret-container-datacenter
    image: debian:latest
    command: ["sleep"]
    args: ["84600"]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
      - name: secret-volume
        mountPath: /opt/games
    ports:
    - containerPort:  80
  volumes:
    - name: secret-volume
      secret:
        secretName: media
