apiVersion: v1
kind: Pod
metadata:
  name: volume-share-xfusion
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
  - name: volume-container-xfusion-1
    image: fedora:latest
    command: ["sleep"]
    args: ["84600"]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/blog
  - name: volume-container-xfusion-2
    image: fedora:latest
    command: ["sleep"]
    args: ["84600"]
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/apps
  volumes:
    - name: volume-share
      emptyDir: {}
  