apiVersion: v1
kind: Pod
metadata:
  name: print-envars-greeting
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
  - name: print-env-container
    image: bash
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 300
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
    readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 300
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
    env:
    - name: GREETING
      value: "Welcome to"
    - name: COMPANY
      value: "Stratos"
    - name: GROUP
      value: "Group"
    command:
      - "echo"
    args:
      - "$(GREETING) $(COMPANY) $(GROUP)"
    ports:
      - containerPort: 80
