- name: sysmlinks for different users
  hosts: all
  become: yes
  tasks:
    - name: create an empty file stapp01
      ansible.builtin.file:
        path:  /opt/dba/blog.txt
        state: touch
        owner: tony
        group: tony
      when: inventory_hostname == "stapp01"
    - name: create symlink
      ansible.builtin.file:
        src: /opt/dba/
        dest: /var/www/html
        state: link
      when: inventory_hostname == "stapp01"
    
    - name: create an empty file stapp02
      ansible.builtin.file:
        path:  /opt/dba/story.txt
        state: touch
        owner: steve
        group: steve
      when: inventory_hostname == "stapp02"
    - name: create symlink
      ansible.builtin.file:
        src: /opt/dba/
        dest: /var/www/html
        state: link
      when: inventory_hostname == "stapp02"

    - name: create an empty file stapp03
      ansible.builtin.file:
        path:  /opt/dba/media.txt
        state: touch
        owner: banner
        group: banner
      when: inventory_hostname == "stapp03"
    - name: create symlink
      ansible.builtin.file:
        src: /opt/dba/
        dest: /var/www/html
        state: link
      when: inventory_hostname == "stapp03"
