apiVersion: apps/v1 
kind: Deployment
metadata:
  name: my-app
  namespace: default
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
    #refernces screts to be used when pulling an image froma private repository if not already configured. 
      # imagePullSecrets:
      #   - 
      containers:
      - name: simple-nodejs-container
      #Declares the pull action of an image
        imagePullPolicy: Always
        image: merch7x/dev-repo:myapp-v1 
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80

